import prisma from "../../prisma/prismaClient.js"

const dogRazasCatalogo = [
    { nombre_raza: "Affenpinscher", tamano: "Pequeño", temperamento: "Curioso, travieso, atrevido", tipo: "Compañía" },
    { nombre_raza: "Afghan Hound", tamano: "Grande", temperamento: "Digno, independiente, leal", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Airedale Terrier", tamano: "Grande", temperamento: "Inteligente, independiente, alegre", tipo: "Terrier" },
    { nombre_raza: "Akita Inu", tamano: "Grande", temperamento: "Digno, leal, reservado", tipo: "Spitz / Trabajo" },
    { nombre_raza: "Alaskan Malamute", tamano: "Grande", temperamento: "Leal, afectuoso, amigable", tipo: "Trabajo (Trineo)" },
    { nombre_raza: "American Bulldog", tamano: "Grande", temperamento: "Seguro, decidido, leal", tipo: "Trabajo" },
    { nombre_raza: "American Pit Bull Terrier", tamano: "Mediano", temperamento: "Entusiasta, fuerte, cariñoso", tipo: "Terrier" },
    { nombre_raza: "American Staffordshire", tamano: "Mediano", temperamento: "Seguro, atento, devoto", tipo: "Terrier" },
    { nombre_raza: "Australian Cattle Dog", tamano: "Mediano", temperamento: "Enérgico, protector, obediente", tipo: "Pastoreo" },
    { nombre_raza: "Australian Shepherd", tamano: "Mediano", temperamento: "Inteligente, activo, trabajador", tipo: "Pastoreo" },
    { nombre_raza: "Basenji", tamano: "Pequeño", temperamento: "Inteligente, independiente, callado", tipo: "Primitivo" },
    { nombre_raza: "Basset Hound", tamano: "Mediano", temperamento: "Tranquilo, tenaz, amigable", tipo: "Sabueso" },
    { nombre_raza: "Beagle", tamano: "Mediano", temperamento: "Curioso, feliz, decidido", tipo: "Sabueso" },
    { nombre_raza: "Bearded Collie", tamano: "Mediano", temperamento: "Alegre, vivaz, adaptable", tipo: "Pastoreo" },
    { nombre_raza: "Beauceron", tamano: "Grande", temperamento: "Decidido, leal, trabajador", tipo: "Pastoreo" },
    { nombre_raza: "Bedlington Terrier", tamano: "Mediano", temperamento: "Atrevido, cariñoso, suave", tipo: "Terrier" },
    { nombre_raza: "Bernese Mountain Dog", tamano: "Gigante", temperamento: "Apacible, afectuoso, estable", tipo: "Montaña" },
    { nombre_raza: "Bichón Frisé", tamano: "Pequeño", temperamento: "Juguetón, alegre, sensible", tipo: "Compañía" },
    { nombre_raza: "Bloodhound", tamano: "Grande", temperamento: "Amable, curioso, independiente", tipo: "Sabueso" },
    { nombre_raza: "Border Collie", tamano: "Mediano", temperamento: "Inteligente, hiperactivo, astuto", tipo: "Pastoreo" },
    { nombre_raza: "Border Terrier", tamano: "Pequeño", temperamento: "Alerta, valiente, amigable", tipo: "Terrier" },
    { nombre_raza: "Borzoi", tamano: "Grande", temperamento: "Reservado, inteligente, veloz", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Boston Terrier", tamano: "Pequeño", temperamento: "Amigable, vivaz, alerta", tipo: "Compañía" },
    { nombre_raza: "Boxer", tamano: "Grande", temperamento: "Juguetón, devoto, valiente", tipo: "Trabajo" },
    { nombre_raza: "Briard", tamano: "Grande", temperamento: "Leal, valiente, protector", tipo: "Pastoreo" },
    { nombre_raza: "Brittany", tamano: "Mediano", temperamento: "Enérgico, sensible, atento", tipo: "Caza (Perdiguero)" },
    { nombre_raza: "Brussels Griffon", tamano: "Pequeño", temperamento: "Alerta, curioso, cariñoso", tipo: "Compañía" },
    { nombre_raza: "Bull Terrier", tamano: "Grande", temperamento: "Travieso, fuerte, cariñoso", tipo: "Terrier" },
    { nombre_raza: "Bulldog Inglés", tamano: "Mediano", temperamento: "Tranquilo, valiente, amigable", tipo: "Compañía" },
    { nombre_raza: "Bulldog Francés", tamano: "Pequeño", temperamento: "Adaptativo, juguetón, inteligente", tipo: "Compañía" },
    { nombre_raza: "Bullmastiff", tamano: "Grande", temperamento: "Leal, valiente, tranquilo", tipo: "Trabajo" },
    { nombre_raza: "Cairn Terrier", tamano: "Pequeño", temperamento: "Valiente, atrevido, alegre", tipo: "Terrier" },
    { nombre_raza: "Cane Corso", tamano: "Grande", temperamento: "Inteligente, estable, decidido", tipo: "Trabajo" },
    { nombre_raza: "Cavalier King Charles", tamano: "Pequeño", temperamento: "Afectuoso, social, paciente", tipo: "Compañía" },
    { nombre_raza: "Chesapeake Bay Retriever", tamano: "Grande", temperamento: "Feliz, activo, protector", tipo: "Deporte" },
    { nombre_raza: "Chihuahua", tamano: "Pequeño", temperamento: "Alerta, rápido, terco", tipo: "Compañía" },
    { nombre_raza: "Chinese Crested", tamano: "Pequeño", temperamento: "Afectuoso, alegre, alerta", tipo: "Compañía" },
    { nombre_raza: "Chow Chow", tamano: "Mediano", temperamento: "Independiente, serio, leal", tipo: "Spitz / Compañía" },
    { nombre_raza: "Cocker Spaniel Americano", tamano: "Pequeño", temperamento: "Feliz, adaptable, juguetón", tipo: "Caza" },
    { nombre_raza: "Cocker Spaniel Inglés", tamano: "Mediano", temperamento: "Amable, sensible, alegre", tipo: "Caza" },
    { nombre_raza: "Collie (Rough)", tamano: "Grande", temperamento: "Leal, protector, inteligente", tipo: "Pastoreo" },
    { nombre_raza: "Dachshund", tamano: "Pequeño", temperamento: "Astuto, vivaz, curioso", tipo: "Sabueso" },
    { nombre_raza: "Dálmata", tamano: "Grande", temperamento: "Juguetón, activo, sensible", tipo: "Compañía / Trabajo" },
    { nombre_raza: "Doberman", tamano: "Grande", temperamento: "Leal, alerta, intrépido", tipo: "Trabajo" },
    { nombre_raza: "Dogo Argentino", tamano: "Grande", temperamento: "Valiente, leal, amable", tipo: "Caza / Trabajo" },
    { nombre_raza: "Dogue de Bordeaux", tamano: "Gigante", temperamento: "Tranquilo, leal, paciente", tipo: "Trabajo" },
    { nombre_raza: "English Foxhound", tamano: "Grande", temperamento: "Activo, resistente, amigable", tipo: "Sabueso" },
    { nombre_raza: "English Setter", tamano: "Grande", temperamento: "Gentil, fuerte, afectuoso", tipo: "Caza" },
    { nombre_raza: "English Springer Spaniel", tamano: "Mediano", temperamento: "Alegre, activo, atento", tipo: "Caza" },
    { nombre_raza: "Fila Brasileiro", tamano: "Grande", temperamento: "Valiente, fiel, decidido", tipo: "Trabajo" },
    { nombre_raza: "Flat-Coated Retriever", tamano: "Grande", temperamento: "Alegre, entusiasta, activo", tipo: "Deporte" },
    { nombre_raza: "Fox Terrier (Pelo de alambre)", tamano: "Pequeño", temperamento: "Alerta, vivaz, rápido", tipo: "Terrier" },
    { nombre_raza: "Fox Terrier (Pelo liso)", tamano: "Pequeño", temperamento: "Alerta, vivaz, rápido", tipo: "Terrier" },
    { nombre_raza: "French Bulldog", tamano: "Pequeño", temperamento: "Adaptativo, juguetón", tipo: "Compañía" },
    { nombre_raza: "Galgo Español", tamano: "Grande", temperamento: "Tranquilo, amable", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Golden Retriever", tamano: "Grande", temperamento: "Amigable, inteligente, devoto", tipo: "Deporte" },
    { nombre_raza: "Gordon Setter", tamano: "Grande", temperamento: "Leal, alerta, seguro", tipo: "Caza" },
    { nombre_raza: "Gran Danés", tamano: "Gigante", temperamento: "Amable, confiable, cariñoso", tipo: "Trabajo" },
    { nombre_raza: "Great Pyrenees", tamano: "Gigante", temperamento: "Serio, tranquilo, paciente", tipo: "Montaña / Guarda" },
    { nombre_raza: "Greyhound", tamano: "Grande", temperamento: "Tranquilo, sociable, amable", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Griffon Nivernais", tamano: "Mediano", temperamento: "Valiente, decidido", tipo: "Sabueso" },
    { nombre_raza: "Havanese", tamano: "Pequeño", temperamento: "Alegre, sociable, adaptable", tipo: "Compañía" },
    { nombre_raza: "Ibizan Hound", tamano: "Grande", temperamento: "Activo, cariñoso, inteligente", tipo: "Sabueso (Primitivo)" },
    { nombre_raza: "Irish Setter", tamano: "Grande", temperamento: "Activo, entusiasta, amigable", tipo: "Caza" },
    { nombre_raza: "Irish Wolfhound", tamano: "Gigante", temperamento: "Dulce, paciente, digno", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Italian Greyhound", tamano: "Pequeño", temperamento: "Dependiente, tranquilo", tipo: "Compañía / Lebrel" },
    { nombre_raza: "Jack Russell Terrier", tamano: "Pequeño", temperamento: "Energético, tenaz, inteligente", tipo: "Terrier" },
    { nombre_raza: "Keeshond", tamano: "Mediano", temperamento: "Alegre, alerta, cariñoso", tipo: "Spitz" },
    { nombre_raza: "Kerry Blue Terrier", tamano: "Mediano", temperamento: "Inteligente, decidido, animado", tipo: "Terrier" },
    { nombre_raza: "Komondor", tamano: "Gigante", temperamento: "Independiente, calmado, protector", tipo: "Pastoreo" },
    { nombre_raza: "Kuvasz", tamano: "Grande", temperamento: "Leal, paciente, protector", tipo: "Trabajo" },
    { nombre_raza: "Labrador Retriever", tamano: "Grande", temperamento: "Juguetón, confiable, activo", tipo: "Deporte" },
    { nombre_raza: "Lakeland Terrier", tamano: "Pequeño", temperamento: "Valiente, amigable, alerta", tipo: "Terrier" },
    { nombre_raza: "Lancashire Heeler", tamano: "Pequeño", temperamento: "Enérgico, inteligente", tipo: "Pastoreo" },
    { nombre_raza: "Leonberger", tamano: "Gigante", temperamento: "Afectuoso, adaptable, leal", tipo: "Montaña" },
    { nombre_raza: "Lhasa Apso", tamano: "Pequeño", temperamento: "Cariñoso, alerta, independiente", tipo: "Compañía" },
    { nombre_raza: "Lowchen", tamano: "Pequeño", temperamento: "Vivaz, afectuoso, inteligente", tipo: "Compañía" },
    { nombre_raza: "Maltese", tamano: "Pequeño", temperamento: "Juguetón, gentil, cariñoso", tipo: "Compañía" },
    { nombre_raza: "Manchester Terrier", tamano: "Pequeño", temperamento: "Vigilante, vivaz", tipo: "Terrier" },
    { nombre_raza: "Mastín Español", tamano: "Gigante", temperamento: "Digno, noble, inteligente", tipo: "Trabajo / Montaña" },
    { nombre_raza: "Mastín Napolitano", tamano: "Gigante", temperamento: "Serio, protector, leal", tipo: "Trabajo" },
    { nombre_raza: "Miniature Pinscher", tamano: "Pequeño", temperamento: "Atrevido, enérgico, alerta", tipo: "Terrier / Compañía" },
    { nombre_raza: "Miniature Schnauzer", tamano: "Pequeño", temperamento: "Alerta, inteligente, obediente", tipo: "Terrier" },
    { nombre_raza: "Newfoundland", tamano: "Gigante", temperamento: "Apacible, dulce, paciente", tipo: "Trabajo / Agua" },
    { nombre_raza: "Norfolk Terrier", tamano: "Pequeño", temperamento: "Alerta, afectuoso, valiente", tipo: "Terrier" },
    { nombre_raza: "Norwegian Buhund", tamano: "Mediano", temperamento: "Atrevido, enérgico, amable", tipo: "Spitz / Pastoreo" },
    { nombre_raza: "Norwegian Elkhound", tamano: "Mediano", temperamento: "Leal, atrevido, independiente", tipo: "Spitz / Caza" },
    { nombre_raza: "Norwich Terrier", tamano: "Pequeño", temperamento: "Encantador, afectuoso", tipo: "Terrier" },
    { nombre_raza: "Old English Sheepdog", tamano: "Grande", temperamento: "Adaptable, inteligente, dócil", tipo: "Pastoreo" },
    { nombre_raza: "Otterhound", tamano: "Grande", temperamento: "Inteligente, amigable, inquieto", tipo: "Sabueso" },
    { nombre_raza: "Papillon", tamano: "Pequeño", temperamento: "Inteligente, alerta, amigable", tipo: "Compañía" },
    { nombre_raza: "Pekingese", tamano: "Pequeño", temperamento: "Orgulloso, afectuoso, leal", tipo: "Compañía" },
    { nombre_raza: "Pembroke Welsh Corgi", tamano: "Pequeño", temperamento: "Alerta, inteligente, activo", tipo: "Pastoreo" },
    { nombre_raza: "Petit Basset Griffon Vendéen", tamano: "Pequeño", temperamento: "Vivaz, amigable, decidido", tipo: "Sabueso" },
    { nombre_raza: "Pointer", tamano: "Grande", temperamento: "Leal, independiente, amigable", tipo: "Caza" },
    { nombre_raza: "Pomerania", tamano: "Pequeño", temperamento: "Extrovertido, vivo, socarrón", tipo: "Spitz / Compañía" },
    { nombre_raza: "Poodle (Caniche)", tamano: "Variable", temperamento: "Inteligente, activo, orgulloso", tipo: "Compañía / Deporte" },
    { nombre_raza: "Portuguese Water Dog", tamano: "Mediano", temperamento: "Inteligente, atrevido, obediente", tipo: "Agua / Trabajo" },
    { nombre_raza: "Presa Canario", tamano: "Grande", temperamento: "Seguro, equilibrado, leal", tipo: "Trabajo" },
    { nombre_raza: "Pug (Carlino)", tamano: "Pequeño", temperamento: "Encantador, travieso, amigable", tipo: "Compañía" },
    { nombre_raza: "Puli", tamano: "Mediano", temperamento: "Inteligente, ágil, acrobático", tipo: "Pastoreo" },
    { nombre_raza: "Rhodesian Ridgeback", tamano: "Grande", temperamento: "Leal, independiente, noble", tipo: "Caza / Guarda" },
    { nombre_raza: "Rottweiler", tamano: "Grande", temperamento: "Protector, confiable, tranquilo", tipo: "Trabajo" },
    { nombre_raza: "Saint Bernard", tamano: "Gigante", temperamento: "Apacible, amable, paciente", tipo: "Trabajo / Montaña" },
    { nombre_raza: "Saluki", tamano: "Grande", temperamento: "Reservado, tranquilo, inteligente", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Samoyedo", tamano: "Grande", temperamento: "Adaptativo, amigable, sociable", tipo: "Trabajo / Spitz" },
    { nombre_raza: "Schipperke", tamano: "Pequeño", temperamento: "Curioso, atrevido, atento", tipo: "Pastor / Guarda" },
    { nombre_raza: "Schnauzer Gigante", tamano: "Grande", temperamento: "Leal, dominante, inteligente", tipo: "Trabajo" },
    { nombre_raza: "Schnauzer Estándar", tamano: "Mediano", temperamento: "Inteligente, alerta, robusto", tipo: "Trabajo" },
    { nombre_raza: "Scottish Terrier", tamano: "Pequeño", temperamento: "Independiente, seguro, alerta", tipo: "Terrier" },
    { nombre_raza: "Sealyham Terrier", tamano: "Pequeño", temperamento: "Alerta, valiente, amigable", tipo: "Terrier" },
    { nombre_raza: "Shar Pei", tamano: "Mediano", temperamento: "Independiente, leal, tranquilo", tipo: "Compañía / Guarda" },
    { nombre_raza: "Shetland Sheepdog", tamano: "Pequeño", temperamento: "Enérgico, dócil, inteligente", tipo: "Pastoreo" },
    { nombre_raza: "Shiba Inu", tamano: "Pequeño", temperamento: "Alerta, atento, simpático", tipo: "Spitz" },
    { nombre_raza: "Shih Tzu", tamano: "Pequeño", temperamento: "Afectuoso, alerta, amigable", tipo: "Compañía" },
    { nombre_raza: "Shikoku", tamano: "Mediano", temperamento: "Alerta, enérgico, leal", tipo: "Spitz / Primitivo" },
    { nombre_raza: "Siberian Husky", tamano: "Grande", temperamento: "Amistoso, travieso, resistente", tipo: "Trabajo (Trineo)" },
    { nombre_raza: "Silky Terrier", tamano: "Pequeño", temperamento: "Alerta, amigable, sociable", tipo: "Terrier" },
    { nombre_raza: "Skye Terrier", tamano: "Mediano", temperamento: "Valiente, leal, serio", tipo: "Terrier" },
    { nombre_raza: "Sloughi", tamano: "Grande", temperamento: "Sensible, inteligente, rápido", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Soft Coated Wheaten Terrier", tamano: "Mediano", temperamento: "Alegre, afectuoso, enérgico", tipo: "Terrier" },
    { nombre_raza: "Spinone Italiano", tamano: "Grande", temperamento: "Paciente, dócil, leal", tipo: "Caza" },
    { nombre_raza: "Staffordshire Bull Terrier", tamano: "Mediano", temperamento: "Valiente, confiable, cariñoso", tipo: "Terrier" },
    { nombre_raza: "Standard Schnauzer", tamano: "Mediano", temperamento: "Leal, alerta, inteligente", tipo: "Trabajo" },
    { nombre_raza: "Sussex Spaniel", tamano: "Mediano", temperamento: "Amigable, leal, tranquilo", tipo: "Caza" },
    { nombre_raza: "Swedish Vallhund", tamano: "Pequeño", temperamento: "Alerta, enérgico", tipo: "Pastoreo" },
    { nombre_raza: "Tibetan Mastiff", tamano: "Gigante", temperamento: "Fuerte, territorial, inteligente", tipo: "Trabajo / Guarda" },
    { nombre_raza: "Tibetan Spaniel", tamano: "Pequeño", temperamento: "Inteligente, confiado", tipo: "Compañía" },
    { nombre_raza: "Tibetan Terrier", tamano: "Mediano", temperamento: "Sensible, devoto, alegre", tipo: "Compañía" },
    { nombre_raza: "Tosa", tamano: "Gigante", temperamento: "Decidido, valiente, tranquilo", tipo: "Trabajo" },
    { nombre_raza: "Toy Fox Terrier", tamano: "Pequeño", temperamento: "Inteligente, alerta, rápido", tipo: "Terrier" },
    { nombre_raza: "Vizsla", tamano: "Mediano", temperamento: "Afectuoso, atlético, leal", tipo: "Caza" },
    { nombre_raza: "Weimaraner", tamano: "Grande", temperamento: "Enérgico, leal, atrevido", tipo: "Caza" },
    { nombre_raza: "Welsh Springer Spaniel", tamano: "Mediano", temperamento: "Amable, afectuoso", tipo: "Caza" },
    { nombre_raza: "Welsh Terrier", tamano: "Pequeño", temperamento: "Valiente, amigable", tipo: "Terrier" },
    { nombre_raza: "West Highland White Terrier", tamano: "Pequeño", temperamento: "Alegre, independiente, valiente", tipo: "Terrier" },
    { nombre_raza: "Whippet", tamano: "Pequeño", temperamento: "Tranquilo, cariñoso, veloz", tipo: "Sabueso (Lebrel)" },
    { nombre_raza: "Wirehaired Pointing Griffon", tamano: "Mediano", temperamento: "Leal, amigable, entrenable", tipo: "Caza" },
    { nombre_raza: "Xoloitzcuintle", tamano: "Variable", temperamento: "Alerta, tranquilo, leal", tipo: "Primitivo / Compañía" },
    { nombre_raza: "Yorkshire Terrier", tamano: "Pequeño", temperamento: "Animado, osado, cariñoso", tipo: "Terrier / Compañía" }
];

async function createBreeads() {
    console.log("Creando catalogo de razas...");

    const razasConAnimal = dogRazasCatalogo.map(raza => ({
        ...raza,
        animal: "Canino"
    }))

    await prisma.cat_Razas.createMany({
        data: razasConAnimal,
        skipDuplicates: true
    })

    console.log("Razas creadas sin duplicados")
}

createBreeads()
    .catch((e) => {
        console.error("Error al crear el catalogo de razas", e)
    })
    .finally( async () => {
        await prisma.$disconnect()
    })